services:
  - type: web
    name: simplebank
    runtime: docker
    plan: free
    region: ohio
    branch: main
    healthCheckPath: /actuator/health
    buildCommand: docker build -t simplebank .
    startCommand: docker run -e PORT=$PORT -p $PORT:$PORT simplebank
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx400m -XX:+UseContainerSupport -Dfile.encoding=UTF-8"
      - key: PORT
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: simplebank_db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: simplebank_db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: simplebank_db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: simplebank_db
          property: host

databases:
  - name: simplebank_db
    plan: free
    ipAllowList: []