services:
  - type: web
    name: simplebank
    runtime: docker
    plan: free
    region: ohio
    branch: main
    healthCheckPath: /actuator/health
    buildCommand: docker build -t simplebank .
    startCommand: docker run -p $PORT:8080 --env-file .env simplebank
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx400m -XX:+UseContainerSupport -Dfile.encoding=UTF-8"
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: simplebank_db
          property: connectionString

databases:
  - name: simplebank_db
    plan: free
    ipAllowList: []