services:
  - type: web
    name: simplebank
    runtime: docker
    plan: free
    region: ohio
    branch: main
    healthCheckPath: /actuator/health
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/*.jar
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: "-Xmx400m -XX:+UseContainerSupport -Dfile.encoding=UTF-8"
      - key: PORT
        value: "10000"
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: simplebank_db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: simplebank_db
          property: username
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: simplebank_db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: simplebank_db
          property: host
      - key: ALLOWED_ORIGIN
        value: "https://${RENDER_EXTERNAL_HOSTNAME}"

databases:
  - name: simplebank_db
    plan: free
    ipAllowList: []