services:
  - type: web
    name: simplebank
    runtime: docker
    plan: free
    region: ohio
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: "10000"
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: simplebank_db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: simplebank_db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: simplebank_db
          property: password

databases:
  - name: simplebank_db
    plan: free
    ipAllowList: []